routes/web.php
<?php


Route::get('/', function () {
    return view('pages.index');
})->name('home');

Route::get('/locator', function () {
    return view('pages.locator');
})->name('locator');


Route::get('/food/{key}', '\\' . \App\Http\Controllers\ProductsAction::class)->name('food');

Route::get('/single_product/{id}', '\\' . \App\Http\Controllers\SingleProductAction::class)->name('single-product');

Route::post('/mail-subscribed', function (\Illuminate\Http\Request $request) {

    $subscriber = new \App\Subscriber();
    $subscriber->email = $request->input('email');
    $subscriber->status = 1;
    $subscriber->save();

    $mail = new \App\Mail\UserSubscribed($request->input('email'));
    \App\Jobs\SendEmail::dispatch($mail)->onQueue('emails');

    return view('pages.mail-subscribed');
})->name('mail-subscribed');

Route::get('/cart/add_to_cart/{id}', '\\' . \App\Http\Controllers\AddToCartAction::class)->name('add-to-cart');

Route::get('/cart', '\\' . \App\Http\Controllers\ShowCartAction::class)->name('cart');

Route::get('/cart/remove/{id}', '\\' . \App\Http\Controllers\RemoveCartAction::class)->name('remove-from-cart');

Route::post('/update_cart', '\\' . \App\Http\Controllers\UpdateCartAction::class)->name('update-cart');

Route::get('/cart/checkout', function (){
    return view('pages.checkout');} )->name('checkout');

Route::post('/cart/checkout', '\\' . \App\Http\Controllers\OrderController::class)->name('checkout');

Route::get('/order_reseived/{id}', function (\Illuminate\Http\Request $request, $id) {
    $order = \App\Order::find($id);
    return view('pages.order', ['order' => $order]);
})->name('order');

Route::get('/blog', '\\' . \App\Http\Controllers\ShowPostsAction::class)->name('blog');

Route::get('/blog/posts_by_autor/{id}', '\\' . \App\Http\Controllers\ShowPostsByAutor::class)->name('posts-by-autor');

Route::get('/blog/posts_by_category/{key}', '\\' . \App\Http\Controllers\ShowPostsByCategory::class)->name('posts-by-category');

Route::get('/blog/single_post/{id}', '\\' . \App\Http\Controllers\ShowSinglePost::class)->name('single-post');

Route::match(['get', 'post'], '/admin/form/new', '\\' . \App\Http\Controllers\FormSaveActionController::class)->name('form-action-new');

Route::match(['get', 'post'], '/admin/form/update/{id?}', '\\' . \App\Http\Controllers\FormUpdateActionController::class)->name('form-action-update');

Route::match(['get'], '/admin/products', '\\' . \App\Http\Controllers\ProductsListAction::class)->name('products-list');

Route::match(['delete'], '/admin/products-delete', function (\Illuminate\Http\Request $request) {
    $product = \App\Product::find($request->input('id'));
    $product->delete();
    return back();
})->name('form-products-list');


//Route::get('pages/login-and-register', '\\' . \App\Http\Controllers\ShowSinglePost::class)-> name ('single-post');


Auth::routes();

Route::get('/admin', 'HomeController@index')->name('admin');

Route::get('searchSimple', 'SearchController@index')->name('searchSimple');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    public function getShortBodyAttribute()
    {
        return mb_substr($this->body, 0, 250);
    }
}

resources/views/Pages/blog.blade.php
@extends ('layout')

@section ('body-classes','blog right-sidebar')

@section('content')

        <div id="content" class="site-content" tabindex="-1">
        <div class="col-full">
            <div class="pizzaro-breadcrumb">
                <nav class="woocommerce-breadcrumb">
                    <a href="{{route('home')}}">Главная</a><span class="delimiter"><i
                                class="po po-arrow-right-slider"></i></span>Блог
                </nav>
            </div>
            <!-- .woocommerce-breadcrumb -->
            <div id="primary" class="content-area">
                <main id="main" class="site-main">
                    <div class="posts">
                        @foreach($posts as $post)
                            <article id="post-359"
                                     class="post-359 post type-post status-publish format-image has-post-thumbnail sticky hentry category-technology tag-event tag-festival tag-music tag-woocommerce post_format-post-format-image">
                                <header class="entry-header">
                                    <div class="media-attachment">
                                        <div class="post-thumbnail">
                                            <a href="{{route('single-post', $post->id)}}">
                                                <img width="1619" height="827" src="{{$post->cover}}"
                                                     class="attachment-full size-full wp-post-image" alt=""/>
                                            </a>
                                        </div>
                                    </div>
                                    <h1 class="alpha entry-title">
                                        <a href="{{route('single-post', $post->id)}}" rel="bookmark"><p
                                                    class="fun-hover">{{$post->title}} </p></a>
                                    </h1>
                                    <div class="entry-meta">
                                        <div class="label">Категории:</div>
                                        @foreach($post->categories as $category)
                                            <div class="cat-links">
                                                <a href="{{route('posts-by-category', $category->key)}}"
                                                   class="fun-hover" rel="category tag">{{$category->categories}}</a>
                                            </div>
                                        @endforeach
                                        <span class="posted-on">
                                 <a href="{{route('single-post', $post->id)}}" rel="bookmark">
                                     </a>
                                   <div class="label">Создан:</div>
                                 <time class="entry-date published"
                                       datetime="{{$post->created_at}}">{{$post->created_at->format('d.m.Y г. в H:i')}}</time>

                                 </span>
                                        <div class="author">
                                            <div class="label">Автор:</div>
                                            <a href="{{route('posts-by-autor', $post->user->id )}}"
                                               title="Posts by {{$post->user->name}}"
                                               rel="author">{{$post->user->name}}</a>
                                        </div>
                                    </div>
                                </header>
                                <!-- .entry-header -->
                                <div class="entry-content">
                                    <p>{{$post->short_body}}...</p>
                                    <div class="post-readmore">
                                        <a href="{{route('single-post', $post->id)}}" class="read-more-text">Читать
                                            далее ...</a>
                                    </div>
                                </div>
                            </article>
                        @endforeach

                        <article id="post-343"
                                 class="post-343 post type-post status-publish format-quote hentry category-links-quotes category-uncategorized tag-awsome tag-bootstrap tag-clean-design tag-woocommerce tag-wordpress post_format-post-format-quote">
                            <h1 style="display:none;">test</h1>
                            <div class="entry-content">
                                <blockquote>
                                    @inject ('quote', 'App\Services\GetRandomQuoteService' )

                                    @foreach($quote->getRandomQuote() as $quotes)

                                        <p> {{$quotes->quote}} </p>
                                        <cite> {{$quotes->autor_name}}</cite>
                                    @endforeach
                                </blockquote>
                            </div>
                            <!-- .entry-content -->
                        </article>

                    </div>

                </main>
                <!-- #main -->
            </div>
            <!-- #primary -->
            @include ('site-bar')

        </div>

        <nav class="woocommerce-pagination">
            <ul class="page-numbers">
                @if ($posts->currentPage()!=1)
                    <li><a class="next page-numbers" href="?page=1">Первая страница</a></li>
                    <li><a class="next page-numbers" href="{{$posts->previousPageUrl()}}"> < </a></li>
                @endif

                @if ($posts->count ()>0)
                    @for ($count=1; $count<=$posts->lastPage(); $count++)
                        <li><a class="page-numbers @if ($count==$posts->currentPage()) current @endif"
                               href="?page={{$count}}">{{$count}}</a></li>

                    @endfor

                @else
                    <h1><font size="15" color="aqua" face="Arial"> Мы работаем над тем, чтобы здесь что-то появилось
                            ;) </font></h1>
                @endif
                @if ($posts->currentPage() != $posts->lastPage())
                    <li><a class="next page-numbers" href="{{$posts->nextPageUrl()}}"> > </a></li>
                    <li><a class="next page-numbers" href="?page={{$posts->lastPage()}}">Последняя страница</a></li>
                @endif
            </ul>
        </nav>


        <!-- #secondary -->
    </div>
    @include('subscribed')
        <br>

        <script src = "/js/hello.js"> </script>
@endsection

resources/views/Pages/cart.blade.php
@extends ('layout')

@section ('body-classes','woocommerce-cart')

@section('content')

    <div id="content" class="site-content" tabindex="-1">
        <div class="col-full">
            <div class="pizzaro-breadcrumb">
                <nav class="woocommerce-breadcrumb">
                    <a href="{{route('home')}}">Главная</a>
                    <span class="delimiter"><i class="po po-arrow-right-slider"></i></span>Корзина
                </nav>
            </div>
            <!-- .woocommerce-breadcrumb -->
            <div id="primary" class="content-area">
                <main id="main" class="site-main">
                    <div class="pizzaro-order-steps">
                        <ul>
                            <li class="cart">
                                <span class="step">1</span>Корзина
                            </li>
                            <li class="checkout">
                                <span class="step">2</span>Оформление заказа
                            </li>
                            <li class="complete">
                                <span class="step">3</span>Заказ оформлен
                            </li>
                        </ul>
                    </div>
                    <div id="post-8" class="post-8 page type-page status-publish hentry">
                        <div class="entry-content">
                            <div class="woocommerce">
                                <form id="checkout" method="post" action="{{route('update-cart')}}">
                                    @csrf
                                    <table class="shop_table shop_table_responsive cart">
                                        <thead>
                                        <tr>
                                            <th class="product-remove">&nbsp;</th>
                                            <th class="product-thumbnail">&nbsp;</th>
                                            <th class="product-name">Заказ</th>
                                            <th class="product-price">Цена</th>
                                            <th class="product-quantity">Количество</th>
                                            <th class="product-subtotal">Итого</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @if ((!Cart::isEmpty()))
                                            @foreach(\Cart::getContent () as $item)
                                                <tr class="cart_item">
                                                    <td class="product-remove">
                                                        <a href="{{ route('remove-from-cart', $item->id) }}"
                                                           class="remove">&times;</a>
                                                    </td>
                                                    <td class="product-thumbnail">
                                                        <a href="single-product-v1.html">
                                                            <img width="180" height="180"
                                                                 src="{{$item->attributes->image}}" alt=""/>
                                                        </a>
                                                    </td>
                                                    <td class="product-name" data-title="Product">
                                                        <a href="single-product-v1.html">{{$item->name}}</a>
                                                        <dl class="variation">
                                                            <dt class="variation-PickSizespanclasswoocommerce-Price-amountamountspanclasswoocommerce-Price-currencySymbol36span2590span">
                                                                Количество (размер):
                                                            </dt>
                                                            <dd class="variation-PickSizespanclasswoocommerce-Price-amountamountspanclasswoocommerce-Price-currencySymbol36span2590span">
                                                                <p>{{$item->attributes->size}}  {{$item->attributes->dimension}}</p>
                                                            </dd>
                                                        </dl>
                                                    </td>
                                                    <td class="product-price" data-title="Price">
                                                        <span class="woocommerce-Price-amount amount"><span
                                                                    class="woocommerce-Price-currencySymbol"></span>{{$item->price}} грн.</span>
                                                    </td>
                                                    <td class="product-quantity" data-title="Quantity">
                                                        <div class="qty-btn">
                                                            <label>Quantity</label>
                                                            <div class="quantity">
                                                                <input type="number" name="items [{{$item->id}}]"
                                                                       value="{{$item->quantity}}" title="Qty"
                                                                       class="input-text qty text"/>
                                                            </div>
                                                        </div>
                                                    </td>
                                                    <td class="product-subtotal" data-title="Total">
                                                    <span class="woocommerce-Price-amount amount"><span
                                                                class="woocommerce-Price-currencySymbol"></span>{{$item->getPriceSum ()}} грн.</span>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        @else
                                            <h3>В Вашей корзине нет заказов</h3>
                                        @endif
                                        <tr>
                                            <td colspan="6" class="actions">
                                                <div class="coupon">
                                                    <label for="coupon_code">Coupon:</label>
                                                    <input type="text" name="coupon_code" class="input-text"
                                                           id="coupon_code" value="" placeholder="Промокод"/>
                                                    <input type="submit" class="button" name="apply_coupon"
                                                           value="Применить промокод"/>
                                                </div>


                                                <div class="wc-proceed-to-checkout">
                                                    <a href="#"
                                                       onclick="document.getElementById('checkout').submit()"
                                                       type="submit" class="button"
                                                       name="update_cart" value="Обновить корзину"> Обновить
                                                        корзину </a>
                                                    <a href="{{route('checkout')}}"
                                                       class="checkout-button button alt wc-forward">Оформить заказ</a>
                                                </div>
                                                <input type="hidden" id="_wpnonce" name="_wpnonce"
                                                       value="21ca9d92f8"/><input type="hidden" name="_wp_http_referer"
                                                                                  value="/pizzaro/cart/"/>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </form>
                                <div class="cart-collaterals">
                                    <div class="cart_totals ">
                                        <h2>К оплате</h2>
                                        <table class="shop_table shop_table_responsive">
                                                                                       </tr>
                                            <tr class="order-total">
                                                <th>Итого:</th>

                                                <td class="product-subtotal" data-title="Total">
                                                    <span class="woocommerce-Price-amount amount"><span
                                                                class="woocommerce-Price-currencySymbol"></span>{{\Cart:: getTotal ()}} грн.</span>
                                                </td>
                                            </tr>
                                        </table>
                                        <div class="wc-proceed-to-checkout">
                                            <a href="{{route('checkout')}}"
                                               class="checkout-button button alt wc-forward">Proceed to Checkout</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- .entry-content -->
                </main><!-- #main -->
            </div>
            <!-- #post-## -->

        </div>
        <!-- #primary -->
    </div>

    <!-- .col-full -->
    </div>
    <!-- #content -->
    @include('subscribed')
@endsection

resources/views/Pages/locator.blade.php
@extends ('layout')

@section ('body-classes','store-locator-page')

@section('content')

    <div id="content" class="site-content" tabindex="-1">
        <div class="col-full">
            <div class="pizzaro-breadcrumb">
                <nav class="woocommerce-breadcrumb">
                    <a href="{{route('home')}}">Главная</a>
                    <span class="delimiter"><i class="po po-arrow-right-slider"></i></span>Мы на карте
                </nav>
            </div>
            <!-- .woocommerce-breadcrumb -->
            <div id="primary" class="content-area">
                <main id="main" class="site-main">
                    <div id="post-537" class="post-537 page type-page status-publish hentry">
                        <header class="entry-header">
                            <h1 class="entry-title">Мы на карте</h1>
                        </header>
                        <!-- .entry-header -->
                        <div class="entry-content">
                            <div id="wpsl-wrap">
                            {{--<div class="wpsl-search wpsl-clearfix ">--}}
                            {{--<div id="wpsl-search-wrap">--}}
                            {{--<div class="wpsl-from">--}}
                            {{--<div class="wpsl-input">--}}
                            {{--<div>--}}
                            {{--<label for="wpsl-search-input">Your location</label>--}}
                            {{--</div>--}}
                            {{--<input id="wpsl-search-input" type="text" value=""--}}
                            {{--name="wpsl-search-input" placeholder="" aria-required="true"/>--}}
                            {{--</div>--}}
                            {{--<div class="wpsl-select-wrap">--}}
                            {{--<div class="wpsl-radius">--}}
                            {{--<label for="wpsl-radius-dropdown">Search radius</label>--}}
                            {{--<div class="wpsl-dropdown">--}}
                            {{--<select id="wpsl-radius-dropdown" class="" name="wpsl-radius">--}}
                            {{--<option value="10">10 km</option>--}}
                            {{--<option value="25">25 km</option>--}}
                            {{--<option selected="selected" value="50">50 km</option>--}}
                            {{--<option value="100">100 km</option>--}}
                            {{--<option value="200">200 km</option>--}}
                            {{--<option value="500">500 km</option>--}}
                            {{--</select>--}}
                            {{--</div>--}}
                            {{--</div>--}}
                            {{--<div class="wpsl-results">--}}
                            {{--<label for="wpsl-results-dropdown">Results</label>--}}
                            {{--<div class="wpsl-dropdown">--}}
                            {{--<select id="wpsl-results-dropdown" class="" name="wpsl-results">--}}
                            {{--<option selected="selected" value="25">25</option>--}}
                            {{--<option value="50">50</option>--}}
                            {{--<option value="75">75</option>--}}
                            {{--<option value="100">100</option>--}}
                            {{--</select>--}}
                            {{--</div>--}}
                            {{--</div>--}}
                            {{--</div>--}}
                            {{--<div class="wpsl-search-btn-wrap">--}}
                            {{--<input id="wpsl-search-btn" type="submit" value="Search">--}}
                            {{--</div>--}}
                            {{--</div>--}}
                            {{--</div>--}}
                            {{--</div>--}}
                            {{--<div id="wpsl-result-list" class="col-md-4 col-sm-6 col-lg-4 col-xs-12">--}}
                            {{--<div id="wpsl-stores">--}}
                            {{--<ul>--}}
                            {{--<li data-store-id="535">--}}
                            {{--<div>--}}
                            {{--<p>--}}
                            {{--<strong>Pizzaro</strong>--}}
                            {{--<span class="wpsl-street">27, Maraicoir Street</span>--}}
                            {{--<span>Chennai Tamil Nadu 600001</span>--}}
                            {{--<span class="wpsl-country">India</span>--}}
                            {{--</p>--}}
                            {{--</div>--}}
                            {{--<div class="wpsl-direction-wrap">2.9 km--}}
                            {{--</div>--}}
                            {{--</li>--}}
                            {{--</ul>--}}
                            {{--</div>--}}
                            {{--</div>--}}
                            {{--<div class="col-md-8 col-sm-6 col-lg-8 col-xs-12 map">--}}
                            <!-- <div id="wpsl-gmap" class="wpsl-gmap-canvas"></div> -->
                                <div class="contact-map">
                                    <div style="overflow:hidden;width: 1260px;height: 792px;">
                                        <iframe width="700" height="440"
                                                src="https://maps.google.com/maps?width=700&amp;height=440&amp;hl=en&amp;q=Odessa%2C%20Ukraine%2C%20Derybasivska%20street%2C%207+(Pizzaro)&amp;ie=UTF8&amp;t=&amp;z=17&amp;iwloc=B&amp;output=embed"
                                                frameborder="0" scrolling="no" marginheight="0"
                                                marginwidth="0"></iframe>
                                        <div>

                                        </div>
                                        <div>

                                        </div>
                                        <style>#gmap_canvas img {
                                                max-width: none !important;
                                                background: none !important
                                            }</style>
                                    </div>
                                    <br/></div>
                            </div>
                        </div>
                    </div>
                    <!-- .entry-content -->
            </div>
            <!-- #post-## -->
            </main>
            <!-- #main -->
        </div>
        <!-- #primary -->
    </div>
    <!-- .col-full -->
    </div>

@endsection

resources/views/Pages/mail-subscribed.blade.php
@extends ('layout')

@section ('body-classes','page-template-template-homepage-v1 home-v1')

@section('content')


    <h1> Благодарим за подписку</h1>
    <h2> Проверь почту - мы выслали тебе промокод на твой первый заказ </h2>

@endsection

resources/views/Pages/posts-by-user.blade.php
@extends ('layout')

@section ('body-classes','blog right-sidebar')

@section('content')

    <div id="content" class="site-content" tabindex="-1">
        <div class="col-full">
            <div class="pizzaro-breadcrumb">
                <nav class="woocommerce-breadcrumb">
                    <a href="{{route('home')}}">Главная</a><span class="delimiter"><i
                                class="po po-arrow-right-slider"></i></span><a href="{{route('blog')}}">Блог</a>
                </nav>
            </div>
            <!-- .woocommerce-breadcrumb -->
            <div id="primary" class="content-area">
                <main id="main" class="site-main">
                    <div class="posts">
                        <h3>Все посты автора </h3>
                        <h1>{{$user->name}}</h1>
                        @foreach($user->posts as $post)
                            <article id="post-359"
                                     class="post-359 post type-post status-publish format-image has-post-thumbnail sticky hentry category-technology tag-event tag-festival tag-music tag-woocommerce post_format-post-format-image">
                                <header class="entry-header">
                                    <div class="media-attachment">
                                        <div class="post-thumbnail">
                                            <a href="{{route('single-post', $post->id)}}">
                                                <img width="1619" height="827" src="{{$post->cover}}"
                                                     class="attachment-full size-full wp-post-image" alt=""/>
                                            </a>
                                        </div>
                                    </div>
                                    <h1 class="alpha entry-title">
                                        <a href="{{route('single-post', $post->id)}}"
                                           rel="bookmark">{{$post->title}}</a>
                                    </h1>
                                    <div class="entry-meta">
                                        <div class="label">Категории:</div>
                                        @foreach($post->categories as $category)
                                            <div class="cat-links">
                                                <a href="{{route('posts-by-category', $category->key)}}"
                                                   rel="category tag">{{$category->categories}}</a>
                                            </div>
                                        @endforeach
                                        <span class="posted-on">
                                            <div class="label">Создан:</div>
                                 <time class="entry-date published"
                                       datetime="{{$post->created_at}}">{{$post->created_at->format('d.m.Y г. в H:i')}}</time>
                                        </span>
                                        <div class="author">
                                            <div class="label">Автор:</div>
                                            {{$post->user->name}}
                                        </div>
                                    </div>
                                </header>
                                <!-- .entry-header -->
                                <div class="entry-content">
                                    <p>{{$post->short_body}} ...</p>
                                    <div class="post-readmore">
                                        <a href="{{route('single-post', $post->id)}}" class="read-more-text">Читать
                                            далее ...</a>
                                    </div>
                                </div>
                            </article>
                        @endforeach
                    </div>
                </main>
                @include('subscribed')
            </div>
            @include ('site-bar')

        </div>
    </div>

@endsection